import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import slika from '../slike/Develope.svg'
import Router from 'next/router'

export default function Home() {
  const [email, setemail] = useState(false)
  const [mail, setmail] = useState('')
  const handle =async ()=>{
      await fetch('/api/users',{
        method:"POST",
        headers:{
          'Content-Type': 'application/json',
        },
        body:JSON.stringify({mail})
      })
      Router.push('https://www.instagram.com/mlstomic')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {email &&
          <div className={styles.absolute}>
            <div className={styles.contmail}>
                <p>Neki kratak mejl zasto da daju mejl</p>
                <input style={{padding:'5px 10px'}} type='email' placeholder='exaple@inkrist.net' value={mail} onChange={(e)=>setmail(e.target.value)} />
                <a onClick={()=>handle()} style={{color:'#fff',backgroundColor:'#6c63ff',padding:'5px 10px', borderRadius:'10px',marginTop:'20px', cursor:'pointer'}}>Link ka dalje </a>
            </div>
          </div>
      }
      <header className={styles.header}>
        <p style={{ fontSize:'20px'}}>Cleaner Smile Teeth Whitening Kit</p>
        <p>Home</p>
      </header>
      <main className={styles.main}>
          <h1 style={{color:'#6c63ff'}} >Ovo je kao neki zapanjujus naslov</h1>
          <div onClick={(e)=>setemail(true)}>
            <Image src={slika} />
          </div>
          <h2 style={{color:'#6c63ff',margin:0,marginTop:'20px'}}>Nesto vezano za tekst</h2>
          <p>Kratak tekst o proizvodu <span onClick={(e)=>setemail(true)}>Klikni da otvoris mejl</span></p>
      </main>
    </div>
  )
}
